---
#-------------------------------
# General Site Settings

title: Barylets
logo:
author: Serhii Barylets
description: Serhii Barylets is a professional QA Engineer, Software Developer and Independent Contractor offering software testing, software development, QA consulting, and test automation services for international web and mobile projects. Based in Slovakia.
email: bsergob@email.com
phone: +421952065382
address: Prešov, Slovakia
# copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
 # - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Serhii <br> QA Engineer

social:
  - { icon: "ti-facebook", link: "https://www.facebook.com/sergej.barylets" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/serhiibarylets/" }
  #- { icon: "ti-instagram", link: "#" }
  #- { icon: "ti-dribbble", link: "#" }
  #- { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I am a detail-oriented engineer with a passion for building robust and reliable software. My diverse background in web technologies and industrial automation has given me a rigorous approach to ensuring quality at every stage of the development process. I help teams release better products, faster.
#blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Analyze project requirements, define testing goals, and create a clear test strategy. I study the product architecture and identify key risk areas to ensure full test coverage."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Develop test cases and automated scripts based on specifications and user flows. I focus on building efficient, reusable, and maintainable QA solutions."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Execute tests, document results, and provide detailed reports with actionable insights. I collaborate with developers and stakeholders to ensure a smooth release process and high product quality."

# My Team Section
#team:
#  - title: "Jack Schenziwe"
#    image: "assets/images/team/member-1.png"
#    designation: "Project Manager"

  #- title: "Julias Carlie"
   # image: "assets/images/team/member-2.png"
    #designation: "Web Developer"

  #- title: "John Doe"
   # image: "assets/images/team/member-3.png"
    #designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
  skills:
  - { name: Manual Testing, color: "#f6d7b0", value: "95%" }            # soft warm beige
  - { name: API Testing (Postman, Swagger), color: "#cbb7f0", value: "90%" }  # pastel lavender
  - { name: Test Automation (Javascript, Typescript, Playwright), color: "#cfeaf4", value: "80%" }  # gentle sky blue
  - { name: Test Case Design & Execution, color: "#fcd5ce", value: "95%" }    # pale peach
  - { name: Bug Tracking (Jira, Monday), color: "#d3f5f2", value: "85%" }     # mint turquoise
  - { name: SDLC & Agile Methodologies, color: "#f6c1d5", value: "90%" }      # soft rose pink
  - { name: Version Control (Git, GitHub), color: "#faedcb", value: "80%" }   # light sand
  - { name: CI/CD & QA Process Integration, color: "#d0e7f9", value: "70%" }  # soft pastel blue
  - { name: Communication & Collaboration, color: "#e0f7cf", value: "95%" }   # pastel green


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Web Developer,
      icon: "icon-1.png",
      date: "Sep 2014 - Jul 2015",
      organization: "OSGA",
    }
  - {
      name: Industrial Automation Service Engineer,
      icon: "icon-2.png",
      date: "Aug 2008 - Mar 2021",
      organization: "NKMZ",
    }
  - {
      name: QA Engineer,
      icon: "icon-3.png",
      date: "Mar 2021 - Present",
      organization: "Independent Contractor",
    }

#-------------------------------
# Education Section

education-title: Education
education:
#  - {
#      name: Marters in UX Design,
#      date: "2006",
#      organization: "Masassusets Institute of Technology",
#    }
  - {
      name: Industrial automation engineering and computer-integrated technologies,
      date: "2003-2008",
      organization: "Donbas State Mechanical Engineering Academy",
    }
  - {
      name: High School Diploma (Physics and Mathematics Specialization),
      date: "2000-2003",
      organization: "Specialized School #35, Kramatorsk, Ukraine",
    }
#  - {
#      name: Secondary School Certificate,
#      date: "1998",
#      organization: "Cardiff School",
#    }

#-------------------------------
# Services Section

services-title: What I Do
services:
  - {
      name: Test Automation,
      icon: ti-settings,
      description: "I build robust and scalable automated test suites for web and mobile apps using frameworks like WebdriverIO and Playwright. This accelerates release cycles and ensures long-term quality.",
      active: true, # Add true to select section
    }
  - {
      name: Manual & Exploratory Testing,
      icon: ti-check-box,
      description: "I provide thorough manual testing to uncover critical bugs and usability issues that automation can miss, ensuring an intuitive and bug-free user experience.",
      active: ,# Add true to select section
    }
  - {
      name: API Testing,
      icon: ti-server,
      description: "I perform in-depth testing of your API endpoints to verify functionality, reliability, and security. This ensures the backbone of your application is stable and communicates correctly.",
      active: ,# Add true to select section
    }
  - {
      name: QA Strategy & Planning,
      icon: ti-direction,
      description: "I help define a clear QA process, create comprehensive test plans, and manage documentation. A solid strategy ensures efficient testing and alignment with business goals.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
#portfolio-home-items:
#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"

#  - image: "assets/images/portfolio/item-2.png"
#    url: "#"

#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"

#  - image: "assets/images/portfolio/item-4.png"
#    url: "#"

#  - image: "assets/images/portfolio/item-5.png"
#    url: "#"

# Portfolio Page
#portfolio-label:
#  - { title: "UI/UX Design", type: "design" }
#  - { title: "BRANDING", type: "branding" }
#  - { title: "ILLUSTRATION", type: "illustration" }

#portfolio-items:
#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
 #     - type: "illustration"

#  - image: "assets/images/portfolio/item-2.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"

#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"

#  - image: "assets/images/portfolio/item-6.png"
#    url: "#"
#    portfolio-type:
 #     - type: "design"
#      - type: "branding"

#  - image: "assets/images/portfolio/item-8.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"

#  - image: "assets/images/portfolio/item-5.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#
#  - image: "assets/images/portfolio/item-1.png"
#    url: "#"
#    portfolio-type:
#      - type: "branding"

#  - image: "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "design"
#      - type: "illustration"
#      - type: "branding"

#  - image: "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "illustration"

#-------------------------------
# Testimonials Section

#testimonial-items:
 # - name: "Jesica Gomez"
  #  image: "assets/images/testimonial/client-1.png"
   # designation: "CEO, Funder"
   # content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#  - name: "Jesica Gomez"
 #   image: "assets/images/testimonial/client-1.png"
  #  designation: "CEO, Funder"
   # content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  #- name: "Jesica Gomez"
  #  image: "assets/images/testimonial/client-1.png"
   # designation: "CEO, Funder"
   # content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section
#-------------------------------
#client-slider-items:
 # - logo: "assets/images/clients-logo/client-logo-1.png"
  #  url: "#"

  #- logo: "assets/images/clients-logo/client-logo-2.png"
  #  url: "#"

  #- logo: "assets/images/clients-logo/client-logo-3.png"
  #  url: "#"

  #- logo: "assets/images/clients-logo/client-logo-4.png"
  #  url: "#"

  #- logo: "assets/images/clients-logo/client-logo-5.png"
  #  url: "#"

  #- logo: "assets/images/clients-logo/client-logo-1.png"
   # url: "#"

  #- logo: "assets/images/clients-logo/client-logo-2.png"
  #  url: "#"

  #- logo: "assets/images/clients-logo/client-logo-3.png"
   # url: "#"

  #- logo: "assets/images/clients-logo/client-logo-4.png"
   # url: "#"

  #- logo: "assets/images/clients-logo/client-logo-5.png"
   # url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: bsergob@gmail.com
